"""Initial migration

Revision ID: 45c6d2df0d6e
Revises:
Create Date: 2023-04-10 12:49:04.975205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "45c6d2df0d6e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_team")
    op.drop_index("ix_teams_name", table_name="teams")
    op.drop_table("teams")
    op.drop_index("ix_players_name", table_name="players")
    op.drop_table("players")
    op.drop_index("ix_games_id", table_name="games")
    op.drop_table("games")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("team1_name", sa.VARCHAR(), nullable=True),
        sa.Column("team2_name", sa.VARCHAR(), nullable=True),
        sa.Column("team1_score", sa.INTEGER(), nullable=True),
        sa.Column("team2_score", sa.INTEGER(), nullable=True),
        sa.Column("date", sa.DATE(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team1_name"],
            ["teams.name"],
        ),
        sa.ForeignKeyConstraint(
            ["team2_name"],
            ["teams.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_games_id", "games", ["id"], unique=False)
    op.create_table(
        "players",
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index("ix_players_name", "players", ["name"], unique=False)
    op.create_table(
        "teams",
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index("ix_teams_name", "teams", ["name"], unique=False)
    op.create_table(
        "player_team",
        sa.Column("team_id", sa.INTEGER(), nullable=True),
        sa.Column("player_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.name"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.name"],
        ),
    )
    # ### end Alembic commands ###
