"""Initial migration

Revision ID: d90a5fca52dd
Revises:
Create Date: 2023-04-10 14:59:39.981058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d90a5fca52dd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player")
    op.drop_table("game")
    op.drop_table("team")
    op.drop_table("score")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "score",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("game_id", sa.INTEGER(), nullable=True),
        sa.Column("round", sa.INTEGER(), nullable=False),
        sa.Column("team_1_score", sa.INTEGER(), nullable=False),
        sa.Column("team_2_score", sa.INTEGER(), nullable=False),
        sa.Column("timestamp", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "team",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "game",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("team1_id", sa.INTEGER(), nullable=True),
        sa.Column("team2_id", sa.INTEGER(), nullable=True),
        sa.Column("team1_score", sa.INTEGER(), nullable=True),
        sa.Column("team2_score", sa.INTEGER(), nullable=True),
        sa.Column("timestamp", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team1_id"],
            ["team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team2_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "player",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("nickname", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###
